name: Microservices CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - charge
          - configserver
          - discovery
          - gateway
          - station
          - user
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes for ${{ matrix.service }}
        id: changes
        run: |
          if git diff --name-only HEAD | grep -q "services/${{ matrix.service }}/"; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Skip if no changes
        if: env.changed == 'false'
        run: echo "No changes detected for ${{ matrix.service }}."

      - name: Run linting
        if: env.changed == 'true'
        run: |
          cd services/${{ matrix.service }}
          mvn checkstyle:checkstyle

      - name: Run unit tests
        if: env.changed == 'true'
        run: |
          cd services/${{ matrix.service }}
          mvn test

      - name: Package application
        if: env.changed == 'true'
        run: |
          cd services/${{ matrix.service }}
          mvn clean install

      - name: Login to Docker Hub
        if: env.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.service }}
        if: env.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
